name: Docker Image CI

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  packages: write

jobs:
  # ===============================================================
  #   Building Dev Image
  # ===============================================================
  build_dev:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # Test of these containers
        include:
          - container: "alpine-dev:latest"
            file: alpine-dev.Dockerfile
          - container: "ubuntu-dev:20"
            file: u20.04-dev.Dockerfile
          - container: "ubuntu-dev:22"
            file: u22.04-dev.Dockerfile
          - container: "ubuntu-dev:23.10"
            file: u23.10-dev.Dockerfile
          - container: "fedora:30"
            file: fedora30-dev.Dockerfile
          - container: "centos-dev:7"
            file: centos7-dev.Dockerfile
          - container: "ubuntu-dev:24"
            file: u24.04-dev.Dockerfile
          - container: "benchmark-dev:latest"
            file: benchmark-dev.Dockerfile

    steps:
      - name: checkout
        uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.actor }}/${{ matrix.container }}
          file: ${{ matrix.file }}
